CREATE OR REPLACE PROCEDURE prcUS208ConfigurarFatoresDeProducao(apl IN FATORES_DE_PRODUCAO.APLICACAO%TYPE, classif IN FATORES_DE_PRODUCAO.CLASSIFICACAO%TYPE, tipof IN FATORES_DE_PRODUCAO.TIPODEFATOR%TYPE ,formul IN FATORES_DE_PRODUCAO.FORMULACAO%TYPE, nomec IN FATORES_DE_PRODUCAO.NOME_COMERCIAL%TYPE, forn IN FATORES_DE_PRODUCAO.FORNECEDOR%TYPE ,fatid out FATORES_DE_PRODUCAO.FATORES_ID%TYPE) as
begin
    SAVEPOINT BefCall;
    INSERT INTO FATORES_DE_PRODUCAO(APLICACAO, CLASSIFICACAO,TIPODEFATOR, FORMULACAO, NOME_COMERCIAL, FORNECEDOR)
    VALUES (apl, classif, tipof, formul, nomec, forn);
    SELECT FATORES_ID
    into fatid
    FROM FATORES_DE_PRODUCAO
    WHERE APLICACAO = apl
      AND CLASSIFICACAO = classif
      AND TIPODEFATOR = tipof
      AND FORMULACAO = formul
      AND NOME_COMERCIAL = nomec
      AND FORNECEDOR = forn
    ORDER BY FATORES_ID DESC FETCH FIRST ROW ONLY;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Novo Fator de Producao');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Fator de Producao nao encontrado');
        ROLLBACK TO SAVEPOINT BefCall;
end;


/

CREATE OR REPLACE PROCEDURE prcUS208ConfigurarElemento(unid IN ELEMENTO.UNIDADE%TYPE, categ IN ELEMENTO.CATEGORIA%TYPE, subst IN ELEMENTO.SUBSTANCIA%TYPE, idelement OUT ELEMENTO.ID_ELEMENTO%TYPE) AS
begin
    SAVEPOINT BEFCALL;
    INSERT INTO ELEMENTO(UNIDADE, CATEGORIA, SUBSTANCIA)
    VALUES(unid, categ,subst);
    SELECT ID_ELEMENTO
    into idelement
    FROM ELEMENTO 
    WHERE UNIDADE = unid
    AND CATEGORIA = categ
    AND SUBSTANCIA = subst
    ORDER BY ID_ELEMENTO DESC FETCH FIRST ROW ONLY;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Novo Elemento');
    EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Elemento nao encontrado');
        ROLLBACK TO SAVEPOINT BefCall;
end;

/


