DROP TABLE Cliente CASCADE CONSTRAINTS;
DROP TABLE Parcela CASCADE CONSTRAINTS;
DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE PRODUCAO CASCADE CONSTRAINTS;
DROP TABLE VENDA CASCADE CONSTRAINTS;
DROP TABLE TEMPO CASCADE CONSTRAINTS;
DROP TABLE HUB CASCADE CONSTRAINTS;