CREATE TABLE Cliente (
  codigo_interno            number(10) GENERATED BY DEFAULT AS IDENTITY, 
  nrEncomendas_ultimoAno    number(10) NOT NULL, 
  valorEncomendas_ultimoAno double precision NOT NULL, 
  plafond                   number(10), 
  nivel                     varchar2(255), 
  tipo_cliente              varchar2(255) NOT NULL, 
  nr_Incidentes             number(10) NOT NULL, 
  nome                      varchar2(255) NOT NULL, 
  nif                       number(10) NOT NULL UNIQUE CHECK(nif not like '%[^0-9]%' AND LENGTH(nif) = 9),
  email                     varchar2(255) NOT NULL UNIQUE CHECK(email like '%@%.%'), 
  ultimo_incidente          date, 
  id_Morada_Correspondencia number(10) NOT NULL, 
  id_Morada_Entrega         number(10) NOT NULL, 
  hub_id                    NUMBER(10) ,
  PRIMARY KEY (codigo_interno));
  
CREATE TABLE Colheita (
  colheitaID    number(10) GENERATED BY DEFAULT AS IDENTITY, 
  data_colheita timestamp(9),
  gestor        varchar2(255) NOT NULL, 
  PRIMARY KEY (colheitaID));
  
CREATE TABLE Cultura (
  codigo_cultura        number(10) GENERATED BY DEFAULT AS IDENTITY, 
  nome_Produto          varchar2(255) NOT NULL, 
  tipo_cultura          varchar2(255) NOT NULL CHECK(tipo_cultura = 'PERMANENTE' OR tipo_cultura = 'TEMPORARIA'), 
  preco                 double precision NOT NULL, 
  quantidade_Armazenada double precision NOT NULL, 
  preco_semente         double precision NOT NULL, 
  PRIMARY KEY (codigo_cultura));
CREATE TABLE Data_Sensor (
  id_Data_Sensor number(10) GENERATED BY DEFAULT AS IDENTITY, 
  sensor_id      number(10) NOT NULL, 
  data           timestamp(0) NOT NULL, 
  medicao        double precision NOT NULL, 
  unidade        varchar2(255) NOT NULL, 
  PRIMARY KEY (id_Data_Sensor));
CREATE TABLE Elemento (
  id_Elemento number(10) GENERATED BY DEFAULT AS IDENTITY, 
  unidade     varchar2(255) NOT NULL, 
  categoria   varchar2(255) NOT NULL, 
  substancia  varchar2(255) NOT NULL, 
  PRIMARY KEY (id_Elemento));
CREATE TABLE EstacaoMeteorologica (
  cod_estacao number(10) GENERATED BY DEFAULT AS IDENTITY, 
  PRIMARY KEY (cod_estacao));
CREATE TABLE Fatores_de_Producao (
  fatores_id     number(10) GENERATED BY DEFAULT AS IDENTITY, 
  aplicacao      varchar2(255) NOT NULL, 
  classificacao  varchar2(255) NOT NULL, 
  tipoDeFator    varchar2(255) NOT NULL, 
  formulacao     varchar2(255) NOT NULL, 
  nome_comercial varchar2(255) NOT NULL, 
  fornecedor     varchar2(255) NOT NULL, 
  operacao       number(10) NOT NULL,
  PRIMARY KEY (fatores_id));
CREATE TABLE Fatores_de_Producao__Parcela (
  fatores_id number(10) NOT NULL, 
  id_parcela number(10) NOT NULL, 
  PRIMARY KEY (fatores_id, 
  id_parcela));
CREATE TABLE Fertilizacao (
  fertilizacao_id  number(10) GENERATED BY DEFAULT AS IDENTITY, 
  tecnica_agricola varchar2(255) NOT NULL, 
  data             timestamp(0) NOT NULL, 
  quantidade       double precision NOT NULL, 
  p_rega_id        number(10) NOT NULL, 
  fatores_id       number(10) NOT NULL, 
  PRIMARY KEY (fertilizacao_id));
CREATE TABLE FichaTecnica (
  fatores_id  number(10) NOT NULL, 
  id_Elemento number(10) NOT NULL, 
  quantidade  double precision NOT NULL, 
  PRIMARY KEY (fatores_id, 
  id_Elemento));
CREATE TABLE Incidente (
  id_incidente   number(10) GENERATED BY DEFAULT AS IDENTITY, 
  id_pedido      number(10) NOT NULL, 
  codigo_interno number(10) NOT NULL, 
  valor          number(10) NOT NULL, 
  data_incidente date NOT NULL, 
  data_liquidada date, 
  PRIMARY KEY (id_incidente));
CREATE TABLE Morada (
  id_Morada     number(10) GENERATED BY DEFAULT AS IDENTITY, 
  codigo_Postal number(10) NOT NULL, 
  rua           varchar2(255) NOT NULL, 
  tipo_Morada   varchar2(255) NOT NULL CHECK(tipo_Morada = 'ENTREGA' OR tipo_Morada = 'CORRESPONDENCIA'), 
  porta         number(10) NOT NULL, 
  PRIMARY KEY (id_Morada));
CREATE TABLE Parcela (
  id_parcela   number(10) GENERATED BY DEFAULT AS IDENTITY, 
  designacao   varchar2(255) NOT NULL, 
  area         number(10) NOT NULL, 
  tipo_cultura varchar2(255) NOT NULL CHECK(tipo_cultura = 'PERMANENTE' OR tipo_cultura = 'TEMPORARIA'), 
  p_rega_id    number(10) NOT NULL,
  PRIMARY KEY (id_parcela));
CREATE TABLE Parcela_Cultura (
  id_parcela         number(10) NOT NULL, 
  codigo_cultura     number(10) NOT NULL, 
  quantidade_Semente double precision NOT NULL, 
  data_Semente       date NOT NULL, 
  PRIMARY KEY (id_parcela, 
  codigo_cultura));
CREATE TABLE Parcela_Cultura_Colheita (
  codigo_cultura number(10) NOT NULL, 
  id_parcela     number(10) NOT NULL, 
  colheitaID     number(10) NOT NULL, 
  quant_colhida  double precision NOT NULL, 
  PRIMARY KEY (codigo_cultura, 
  id_parcela, 
  colheitaID));
CREATE TABLE Pedido (
  id_pedido             number(10) GENERATED BY DEFAULT AS IDENTITY, 
  data                  date NOT NULL, 
  preco                 double precision NOT NULL, 
  data_pagamento_limite date NOT NULL, 
  estado_pagamento      number(1) NOT NULL, 
  estado_entrega        varchar2(255) NOT NULL CHECK(estado_entrega = 'ENTREGUE' OR estado_entrega = 'REGISTADA' OR estado_entrega = 'PAGA'), 
  data_entrega          date, 
  data_pagamento        date, 
  data_entrega_prevista date, 
  codigo_interno        number(10) NOT NULL, 
  id_Morada             number(10), 
  hub_id         number(10), 
  PRIMARY KEY (id_pedido));
CREATE TABLE Pedido_Cultura (
  id_pedido      number(10) NOT NULL, 
  codigo_cultura number(10) NOT NULL, 
  quantidade     double precision NOT NULL, 
  PRIMARY KEY (id_pedido, 
  codigo_cultura));
CREATE TABLE PlanoDeRega (
  p_rega_id      number(10) GENERATED BY DEFAULT AS IDENTITY, 
  tempos_de_rega double precision NOT NULL, 
  periodicidade  number(10) NOT NULL, 
  ordem_rega     varchar2(255) NOT NULL, 
  data_rega      timestamp(0) NOT NULL, 
  s_rega_id      number(10) NOT NULL, 
  cod_estacao    number(10) NOT NULL, 
  PRIMARY KEY (p_rega_id));
CREATE TABLE Sensor (
  sensor_id           number(10) GENERATED BY DEFAULT AS IDENTITY, 
  tipo_sensor         varchar2(255) NOT NULL, 
  unidade             varchar2(10) NOT NULL, 
  medicao             double precision NOT NULL, 
  valor_de_referencia double precision NOT NULL, 
  cod_estacao         number(10) NOT NULL, 
  PRIMARY KEY (sensor_id));
CREATE TABLE SistemaDeRega (
  s_rega_id       number(10) GENERATED BY DEFAULT AS IDENTITY, 
  qualidade_agua  varchar2(255) NOT NULL CHECK(qualidade_agua = 'muito boa' OR qualidade_agua = 'boa' OR qualidade_agua = 'aceitavel' OR qualidade_agua = 'ma' OR qualidade_agua = 'muito ma'),
  dimensao        number(10) NOT NULL, 
  tipo_rega       varchar2(255) NOT NULL, 
  quantidade_agua double precision NOT NULL, 
  unidade         varchar2(255) NOT NULL, 
  PRIMARY KEY (s_rega_id));
  
CREATE TABLE Operacao (
  op_id   number(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  estado  varchar2(255) NOT NULL CHECK ( estado = 'CANCELADA' OR estado = 'PENDENTE' OR estado = 'REALIZADA'),
  quant   number(10) NOT NULL,
  tecnica varchar2(255) NOT NULL,
  data_prevista    DATE NOT NULL,
  data_execucao   DATE NOT NULL,
  tipoAplicacao varchar2(255) NOT NULL CHECK (tipoAplicacao = 'fertirrega' OR tipoAplicacao = 'foliar' OR tipoAplicacao = 'direta'),
  id_parcela number(10) NOT NULL
  );
  

CREATE TABLE Restricao(
 id_restricao		number(10) GENERATED BY DEFAULT AS IDENTITY,                      
 id_parcela          number(10) NOT NULL,
 fatores_id			number(10) NOT NULL,
 descricao			varchar2(255) NOT NULL,
 data_inicio		date ,
 data_fim 			date,
 quantidade			number(10),
 PRIMARY KEY (id_parcela,fatores_id,id_restricao));

CREATE TABLE Utilizador(
id number(10) GENERATED BY DEFAULT AS IDENTITY,
email varchar(255) NOT NULL CHECK(email like '%@%.%'),
password varchar(255) NOT NULL,
data_login TIMESTAMP NOT NULL,
PRIMARY KEY (id));
 
CREATE TABLE Auditoria(
id_auditoria number(10) GENERATED BY DEFAULT AS IDENTITY,
data_hora TIMESTAMP NOT NULL,
tipo_alteracao VARCHAR(255) NOT NULL CHECK(tipo_alteracao = 'INSERT' OR tipo_alteracao  = 'UPDATE' OR tipo_alteracao = 'DELETE'),
login number(10) NOT NULL,
op_id number(10) NOT NULL,
id_parcela number(10) NOT NULL,
PRIMARY KEY (id_auditoria));

CREATE TABLE Hub ( 
loc_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
latitude DOUBLE PRECISION NOT NULL, 
longitude DOUBLE PRECISION NOT NULL ); 

ALTER TABLE Cliente ADD CONSTRAINT FKClienteHubloc_id FOREIGN KEY (hub_id) REFERENCES Hub (loc_id);  
ALTER TABLE Pedido ADD CONSTRAINT FKPedidoHubloc_id FOREIGN KEY (hub_id) REFERENCES Hub (loc_id);  
ALTER TABLE PlanoDeRega ADD CONSTRAINT FKPlanoDeReg801190 FOREIGN KEY (s_rega_id) REFERENCES SistemaDeRega (s_rega_id);
ALTER TABLE Parcela ADD CONSTRAINT FKParcela167072 FOREIGN KEY (p_rega_id) REFERENCES PlanoDeRega (p_rega_id);
ALTER TABLE Fertilizacao ADD CONSTRAINT FKFertilizac314195 FOREIGN KEY (p_rega_id) REFERENCES PlanoDeRega (p_rega_id);
ALTER TABLE Parcela_Cultura_Colheita ADD CONSTRAINT FKParcela_Cu356983 FOREIGN KEY (codigo_cultura) REFERENCES Cultura (codigo_cultura);
ALTER TABLE Parcela_Cultura_Colheita ADD CONSTRAINT FKParcela_Cu50598 FOREIGN KEY (id_parcela) REFERENCES Parcela (id_parcela);
ALTER TABLE Fatores_de_Producao__Parcela ADD CONSTRAINT FKFatores_de164633 FOREIGN KEY (fatores_id) REFERENCES Fatores_de_Producao (fatores_id);
ALTER TABLE Fatores_de_Producao__Parcela ADD CONSTRAINT FKFatores_de534792 FOREIGN KEY (id_parcela) REFERENCES Parcela (id_parcela);
ALTER TABLE Fertilizacao ADD CONSTRAINT FKFertilizac899874 FOREIGN KEY (fatores_id) REFERENCES Fatores_de_Producao (fatores_id);
ALTER TABLE Pedido ADD CONSTRAINT FKPedido677793 FOREIGN KEY (codigo_interno) REFERENCES Cliente (codigo_interno);
ALTER TABLE Data_Sensor ADD CONSTRAINT FKData_Senso958134 FOREIGN KEY (sensor_id) REFERENCES Sensor (sensor_id);
ALTER TABLE Incidente ADD CONSTRAINT FKIncidente281865 FOREIGN KEY (id_pedido) REFERENCES Pedido (id_pedido);
ALTER TABLE Incidente ADD CONSTRAINT FKIncidente869328 FOREIGN KEY (codigo_interno) REFERENCES Cliente (codigo_interno);
ALTER TABLE Pedido_Cultura ADD CONSTRAINT FKPedido_Cul179230 FOREIGN KEY (id_pedido) REFERENCES Pedido (id_pedido);
ALTER TABLE Pedido_Cultura ADD CONSTRAINT FKPedido_Cul651883 FOREIGN KEY (codigo_cultura) REFERENCES Cultura (codigo_cultura);
ALTER TABLE Pedido ADD CONSTRAINT FKPedido477062 FOREIGN KEY (id_Morada) REFERENCES Morada (id_Morada);
ALTER TABLE Cliente ADD CONSTRAINT FKCliente467072 FOREIGN KEY (id_Morada_Correspondencia) REFERENCES Morada (id_Morada);
ALTER TABLE Cliente ADD CONSTRAINT FKCliente760710 FOREIGN KEY (id_Morada_Entrega) REFERENCES Morada (id_Morada);
ALTER TABLE Parcela_Cultura_Colheita ADD CONSTRAINT FKParcela_Cu340371 FOREIGN KEY (colheitaID) REFERENCES Colheita (colheitaID);
ALTER TABLE Sensor ADD CONSTRAINT FKSensor558872 FOREIGN KEY (cod_estacao) REFERENCES EstacaoMeteorologica (cod_estacao);
ALTER TABLE PlanoDeRega ADD CONSTRAINT FKPlanoDeReg693999 FOREIGN KEY (cod_estacao) REFERENCES EstacaoMeteorologica (cod_estacao);
ALTER TABLE Parcela_Cultura ADD CONSTRAINT FKParcela_Cu475969 FOREIGN KEY (id_parcela) REFERENCES Parcela (id_parcela);
ALTER TABLE Parcela_Cultura ADD CONSTRAINT FKParcela_Cu782354 FOREIGN KEY (codigo_cultura) REFERENCES Cultura (codigo_cultura);
ALTER TABLE FichaTecnica ADD CONSTRAINT FKFichaTecni355332 FOREIGN KEY (fatores_id) REFERENCES Fatores_de_Producao (fatores_id);
ALTER TABLE FichaTecnica ADD CONSTRAINT FKFichaTecni276191 FOREIGN KEY (id_Elemento) REFERENCES Elemento (id_Elemento);
ALTER TABLE Fatores_De_Producao ADD CONSTRAINT FKFatores_De_ProducaoOperacaoop_id FOREIGN KEY (operacao) REFERENCES Operacao (op_id);
ALTER TABLE Operacao ADD CONSTRAINT FKOperacaParcelaid_parcela FOREIGN KEY (id_parcela) REFERENCES Parcela (id_parcela);
ALTER TABLE RESTRICAO ADD CONSTRAINT FKrestricao_de164633 FOREIGN KEY (fatores_id) REFERENCES Fatores_de_Producao (fatores_id);
ALTER TABLE RESTRICAO ADD CONSTRAINT FKrestricao_de534792 FOREIGN KEY (id_parcela) REFERENCES Parcela (id_parcela);
ALTER TABLE AUDITORIA ADD CONSTRAINT FKAuditoriaOperacaoop_id FOREIGN KEY (op_id) REFERENCES OPERACAO (op_id);
ALTER TABLE AUDITORIA ADD CONSTRAINT FKAuditoriaParcelaid_parcela FOREIGN KEY (id_parcela) REFERENCES Parcela (id_parcela);




CREATE TABLE Auditoria_Temp (
  data_hora       timestamp(9) NOT NULL,
  tipo_alteracao  varchar2(255) NOT NULL,
  id_parcela      number(10) NOT NULL,
  login           number(10) NOT NULL,
  op_id           number(10) NOT NULL
);