CREATE OR REPLACE PROCEDURE prcUS206CriarParcela(design IN PARCELA.DESIGNACAO%TYPE, ar IN PARCELA.AREA%TYPE, tipocult IN PARCELA.TIPO_CULTURA%TYPE, pregaid  IN PARCELA.P_REGA_ID%TYPE ,parcelaid out PARCELA.ID_PARCELA%TYPE) as
begin
    SAVEPOINT BefCall;
    INSERT INTO PARCELA(DESIGNACAO, AREA, TIPO_CULTURA, P_REGA_ID)
    VALUES (design, ar, tipocult, pregaid);
    SELECT ID_PARCELA
    into parcelaid
    FROM PARCELA
    WHERE DESIGNACAO = design
      AND AREA = ar
      AND TIPO_CULTURA = tipocult
    ORDER BY ID_PARCELA DESC FETCH FIRST ROW ONLY;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Nova Parcela');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Parcela não encontrada');
        ROLLBACK TO SAVEPOINT BefCall;
end;